export const AUTH_LOADING = 'AUTH_LOADINGS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USER_LOADING = 'USER_LOADING';
export const USER_FAILED = 'USER_FAILED';
export const USER_LOADED = 'USER_LOADED';

export const PROJECT_LOADING = 'PROJECT_LOADING';
export const PROJECT_FAILED = 'PROJECT_FAILED';
export const PROJECT_LOADED = 'PROJECT_LOADED';
export const PROJECT_SELECTED = 'PROJECT_SELECTED';
export const PROJECT_CREATED = 'PROJECT_CREATED';
export const PROJECT_UPDATED = 'PROJECT_UPDATED';
export const PROJECT_DELETED = 'PROJECT_DELETED';

export const PROJECT_EVENT_LOADING = 'PROJECT_EVENT_LOADING';
export const PROJECT_EVENT_FAILED = 'PROJECT_EVENT_FAILED';
export const PROJECT_EVENT_LOADED = 'PROJECT_EVENT_LOADED';
export const PROJECT_EVENT_SELECTED = 'PROJECT_EVENT_SELECTED';
export const PROJECT_EVENT_CREATED = 'PROJECT_EVENT_CREATED';
export const PROJECT_EVENT_UPDATED = 'PROJECT_EVENT_UPDATED';
export const PROJECT_EVENT_DELETED = 'PROJECT_EVENT_DELETED';
export const PROJECT_EVENT_FILTERED = 'PROJECT_EVENT_FILTERED';
export const PROJECT_EVENT_SORTED = 'PROJECT_EVENT_SORTED';
export const PROJECT_EVENT_NEXT_PAGE = 'PROJECT_EVENT_NEXT_PAGE';
export const PROJECT_EVENT_PREV_PAGE = 'PROJECT_EVENT_PREV_PAGE';

export const PROJECT_EVENT_ATTRIBUTE_LOADING = 'PROJECT_EVENT_ATTRIBUTE_LOADING';
export const PROJECT_EVENT_ATTRIBUTE_FAILED = 'PROJECT_EVENT_ATTRIBUTE_FAILED';
export const PROJECT_EVENT_ATTRIBUTE_LOADED = 'PROJECT_EVENT_ATTRIBUTE_LOADED';
export const PROJECT_EVENT_ATTRIBUTE_SELECTED = 'PROJECT_EVENT_ATTRIBUTE_SELECTED';
export const PROJECT_EVENT_ATTRIBUTE_CREATED = 'PROJECT_EVENT_ATTRIBUTE_CREATED';
export const PROJECT_EVENT_ATTRIBUTE_UPDATED = 'PROJECT_EVENT_ATTRIBUTE_UPDATED';
export const PROJECT_EVENT_ATTRIBUTE_DELETED = 'PROJECT_EVENT_ATTRIBUTE_DELETED';
